### ISSUE TITLE
Bug : 文字过长的时候，显示会错乱

### ISSUE THREAD

**Issue by metromancn** [gjiazhe/WaveSideBar#3]
首先感谢gjiazhe的WaveSideBar，我们在新版本"地铁通-MetroMan"中使用了WaveSideBar，非常棒。
http://android.myapp.com/myapp/detail.htm?apkName=com.xinlukou.metroman

然后提一个BUG：
当WaveSideBar中的文字过长的时候，显示会错乱。比如我们使用WaveSideBar显示地铁路线名称时，超过5个字符就会非规则显示。

**Comment by gjiazhe** [comment]
谢谢反馈，可否提供一下截图呢？
我这边试了一下并没有发现非规则显示的情况。

**Comment by metromancn** [comment]
刚才的地铁通-metroman，当选择台北市时，车站页面就会出现这个现象。
具体截图晚上发你。
非常棒的Open Source，感谢

**Comment by metromancn** [comment]
不好意思，这个问题我们再次确认过了，仅在一台安卓4.3的三星S3设备上出现过，在目前的主流安卓6.0上是没有问题的。

**Comment by gjiazhe** [comment]
在其他4.3的设备上会出现这个问题么，抱歉我这边没有多余的设备可以测试

**Comment by gjiazhe** [comment]
Closed because no more response.
