### ISSUE TITLE
间隙问题

### ISSUE THREAD

**Issue by hegelsu** [gjiazhe/WaveSideBar#4]
不知道是什么原因，1为初始化的时候，2为随便选择了一个之后，间隙不知道为什么就变大了
![1](https://cloud.githubusercontent.com/assets/6879123/20856867/8a2f23ee-b956-11e6-96ea-8d702c00a1bb.png)
![2](https://cloud.githubusercontent.com/assets/6879123/20856868/8a418fc0-b956-11e6-91bd-e6f1092faa13.png)
![3](https://cloud.githubusercontent.com/assets/6879123/20856884/f72001a8-b956-11e6-963d-d12abda5971d.png)

**Comment by gjiazhe** [comment]
我大概知道问题出在什么地方了，但需要更多的信息，是否可以提供一下你在 OnSelectIndexItemListener 中的代码呢？如果不方便在这里公开你的代码，可以发邮件给我。多谢！

**Comment by hegelsu** [comment]
![4](https://cloud.githubusercontent.com/assets/6879123/20857362/92201762-b964-11e6-8924-0f8010aea1b3.png)

**Comment by gjiazhe** [comment]
提交了一个新的版本，请更新一下看看是否修复了你的问题。

**Comment by hegelsu** [comment]
解决了，非常感谢。这个组件不错，赞一个。
