### ISSUE TITLE
Pixel手机+Android7.0无法正常显示

### ISSUE THREAD

**Issue by metromancn** [gjiazhe/WaveSideBar#7]
比如显示ABCD......Z时，6.0版会在屏幕中间显示，Pixel手机+Android7.0测试时总是顶着状态栏显示，无法居中。

**Comment by metromancn** [comment]
问题现象截图如下：
[https://github.com/metromancn/Temp/blob/master/WaveSideBar_Bug001.png](url)
[https://github.com/metromancn/Temp/blob/master/WaveSideBar_Bug002.png](url)

**Comment by gjiazhe** [comment]
请为布局文件中的 WaveSideBar 加上 android:layout_below = "@id/toolbar" 属性

**Comment by metromancn** [comment]
加了也没有用。只对Android7.0+才会出现这样的现象。Android6.0,5.0都正常。

**Comment by gjiazhe** [comment]
在
<include layout="@layout/include_toolbar" android:id="@+id/toolbar"/>
中加入 
android:layout_height="wrap_content"
android:layout_width="match_parent"

**Comment by gjiazhe** [comment]
在
`<include layout="@layout/include_toolbar" android:id="@+id/toolbar"/>`
中加入
`android:layout_height="wrap_content"
android:layout_width="match_parent"`

**Comment by gjiazhe** [comment]
然后 WaveSideBar 加上 android:layout_below = "@id/toolbar"

**Comment by metromancn** [comment]
神奇的好了，谢谢大神。看来是由于我使用了include，它的layout属性写在了include文件里面，安卓7.0时外面的页面无法自动识别。

**Comment by metromancn** [comment]
修正后的页面显示如下图：
[https://github.com/metromancn/Temp/blob/master/WaveSideBar_OK002.png](url)
